name: Lint Reusable

on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string
      go-version:
        required: true
        type: string
      golangci-lint-version:
        required: true
        type: string

jobs:
  golangci-lint:
    name: Lint all Go modules
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4.2.2

      - name: 🗄️ Cache Go modules
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', 'go.work.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: 🛠 Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: ${{ inputs.go-version }}

      - name: 🐾 Show go.work (debug)
        run: cat go.work || echo "❗ go.work not found"

      - name: 🔄 Install dependencies
        run: |
          # Используем go work для установки зависимостей всех модулей
          go work sync

      - name: 📌 Install Task
        uses: arduino/setup-task@v2.0.0

      - name: ✅ Run golangci-lint via Taskfile
        id: lint_step
        continue-on-error: true
        env:
          MODULES: ${{ inputs.modules }}
          GOLANGCI_LINT_VERSION: ${{ inputs.golangci-lint-version }}
        run: |
          # Создаем директорию для отчетов
          mkdir -p .github_pages/lint
          
          # Запускаем линтер и сохраняем результат
          echo "🔍 Запуск golangci-lint..."
          if task lint > lint_output.txt 2>&1; then
            echo "✅ Линт прошел успешно"
            echo "LINT_STATUS=success" >> $GITHUB_OUTPUT
            lint_result="success"
          else
            echo "❌ Найдены ошибки линтинга"
            echo "LINT_STATUS=failure" >> $GITHUB_OUTPUT 
            lint_result="failure"
          fi
          
          # Создаем HTML отчет
          cat > .github_pages/lint/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="ru">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>🔍 Lint Report</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
                      line-height: 1.6;
                      color: #24292f;
                      max-width: 1200px;
                      margin: 0 auto;
                      padding: 20px;
                      background: #ffffff;
                  }
                  .header {
                      text-align: center;
                      padding: 20px 0;
                      border-bottom: 2px solid #e1e4e8;
                      margin-bottom: 30px;
                  }
                  .status-success {
                      background: #dcfce7;
                      color: #15803d;
                      padding: 12px 20px;
                      border-radius: 8px;
                      border: 1px solid #bbf7d0;
                  }
                  .status-failure {
                      background: #fef2f2;
                      color: #dc2626;
                      padding: 12px 20px;
                      border-radius: 8px;
                      border: 1px solid #fecaca;
                  }
                  .report-content {
                      background: #f6f8fa;
                      padding: 20px;
                      border-radius: 8px;
                      border: 1px solid #d1d9e0;
                      font-family: 'SF Mono', Consolas, monospace;
                      white-space: pre-wrap;
                      font-size: 14px;
                      overflow-x: auto;
                  }
                  .info {
                      background: #f0f9ff;
                      color: #0369a1;
                      padding: 12px 20px;
                      border-radius: 8px;
                      border: 1px solid #bae6fd;
                      margin: 20px 0;
                  }
                  .navigation {
                      text-align: center;
                      margin: 30px 0;
                  }
                  .nav-link {
                      display: inline-block;
                      margin: 0 10px;
                      padding: 8px 16px;
                      background: #f6f8fa;
                      color: #24292f;
                      text-decoration: none;
                      border-radius: 6px;
                      border: 1px solid #d1d9e0;
                  }
                  .nav-link:hover {
                      background: #e1e4e8;
                  }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>🔍 Lint Report</h1>
          EOF
          
          # Добавляем статус в HTML
          if [ "$lint_result" = "success" ]; then
              echo '        <div class="status-success">✅ Линтинг прошел успешно - ошибок не найдено</div>' >> .github_pages/lint/index.html
          else
              echo '        <div class="status-failure">❌ Обнаружены ошибки линтинга</div>' >> .github_pages/lint/index.html
          fi
          
          # Завершаем header и добавляем навигацию
          cat >> .github_pages/lint/index.html << 'EOF'
              </div>
          
              <div class="navigation">
                  <a href="../" class="nav-link">📊 Coverage Report</a>
                  <a href="../tests/" class="nav-link">🧪 Test Report</a>
                  <a href="./" class="nav-link">🔍 Lint Report</a>
              </div>
          
              <div class="info">
                  <strong>Отчет сгенерирован:</strong> 
          EOF
          
          echo "$(date)" >> .github_pages/lint/index.html
          echo '<br><strong>Commit:</strong> ${{ github.sha }}' >> .github_pages/lint/index.html
          echo '<br><strong>Branch:</strong> ${{ github.ref_name }}' >> .github_pages/lint/index.html
          
          cat >> .github_pages/lint/index.html << 'EOF'
              </div>
          
              <h2>📋 Результаты линтинга:</h2>
              <div class="report-content">
          EOF
          
          # Добавляем результат линтинга в HTML, экранируя HTML символы
          if [ -f lint_output.txt ]; then
              sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' lint_output.txt >> .github_pages/lint/index.html
          else
              echo "Результаты линтинга недоступны" >> .github_pages/lint/index.html
          fi
          
          cat >> .github_pages/lint/index.html << 'EOF'
              </div>
          </body>
          </html>
          EOF
          
          echo "📊 HTML отчет создан: .github_pages/lint/index.html"

      - name: 📤 Upload lint report artifact
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: |
            .github_pages/lint/
            lint_output.txt
          retention-days: 30

      - name: 📋 Show lint summary
        run: |
          echo "🔍 Lint Summary:"
          echo "Status: ${{ steps.lint_step.outputs.LINT_STATUS }}"
          if [ -f lint_output.txt ]; then
            echo "📄 Output preview (last 10 lines):"
            tail -10 lint_output.txt
          fi